name: Java CI with Maven java 8

on:
  push:
   branches: [ "main" ]
   paths: 
    - 'src/main/java/com/example/springboot/Application.java'
  pull_request:
    branches: [ "main" ]
    paths: 
     - 'src/main/java/com/example/springboot/Application.java'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven java 8
      run: mvn install
    - name: run application on maven tomcat
      run: mvn spring-boot:run
