name: Java CI with Maven

on:
  push:
   paths: 
    - 'src/main/java/com/example/springboot/HelloController.java'
  pull_request:
    paths: 
     - 'src/main/java/com/example/springboot/HelloController.java'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven with java 11
      run: mvn install
    - name: run application on maven tomcat
      run: mvn spring-boot:run
